pname: glucosedao
channels:
- pytorch
- anaconda
- conda-forge
- defaults
dependencies:
  - python==3.10
  - #pytorch==2.3.0
  - pytorch-gpu
  - pytorch-lightning<3
  - matplotlib
  - optuna
  - numpy<2
  - xgboost<2.1
  - pandas<2.2  # Removed from Pip
  - darts
  - statsmodels
  - statsforecast  # Removed from Pip
  - pip
  - pip:
    - typer
    - pillow==10.3.0
    - pmdarima==2.0.4
    - PyYAML==6.0.1
    - requests==2.31.0
    - scikit-learn==1.4.2
    - scipy==1.13.0
    - seaborn==0.13.2
    - torchmetrics==1.3.2
    - torchvision==0.18.0  # Removed from Pip
    - tqdm==4.66.4
  
  #micromamba install-c conda-forge -c default cudatoolkit (800mb)
  #sudo apt install nvidia-cuda-toolkit